name: Deploy DOCs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'APIs/**.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: ./APIs/openapi.json
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui